facebook :
  client :
#    client-id: 105872199494230
#    client-secret: 2c4a7c46e879bf7fdfa416e5a5ed5793
    client-id : 785290518285386
    client-secret: d6e6278de41fa68f79dfedaa2a89dc19
    access-token-uri: https://graph.facebook.com/oauth/access_token
    user-authorization-uri: https://www.facebook.com/dialog/oauth?display=popup
    token-name: oauth_token
    authentication-scheme: query
    client-authentication-scheme: form
    scope: publish_actions, public_profile, email
  resource:
    user-info-uri: https://graph.facebook.com/me
server:
  port: 80

#twitter:
#  client:
#      client-id: UkCGdoA6PLJvnjC2jDwQ86tar
#      client-secret: e3YwL5IdjAdMXJ9VrStykDwEsBquT8ecENpfDddm8kBS6eDvxw
#      request-token-url: https://api.twitter.com/oauth/request_token
#      authenticate-token-url: https://api.twitter.com/oauth/authenticate
#      access-token-url: https://api.twitter.com/oauth/access_token
#      authorization-uri: https://api.twitter.com/oauth/authorize
#      token-name: oauth_token
#      authentication-scheme: query
#      client-authentication-scheme: form
#  resource:
#      user-info-uri: https://api.twitter.com/oauth/token