server:
  port: 8080

facebook :
  client :
    client-id : 465358593799840
    client-secret: a37286e3dae00dcdce628f40dfe363f5
    access-token-uri: https://graph.facebook.com/oauth/access_token
    user-authorization-uri: https://www.facebook.com/dialog/oauth?display=popup
    token-name: oauth_token
    authentication-scheme: query
    client-authentication-scheme: form
    scope: publish_actions, public_profile, email
  resource:
    user-info-uri: https://graph.facebook.com/me

twitter:
  client:
#    client-id: UkCGdoA6PLJvnjC2jDwQ86tar
#    client-secret: e3YwL5IdjAdMXJ9VrStykDwEsBquT8ecENpfDddm8kBS6eDvxw
#    request-token-url: https://api.twitter.com/oauth/request_token
#    authenticate-token-url: https://api.twitter.com/oauth/authenticate
    client-id: qynoCusuv0j4RsAEc4QEKHJBb
    client-secret: Z5Qc2wWqLd78ZSIGZt49gElElOAcYMY8dIYnWhz96MKnicueDO
    access-token-uri: https://api.twitter.com/oauth/access_token
    user-authorization-uri: https://api.twitter.com/oauth/authorize
    token-name: oauth_token
    authentication-scheme: query
    client-authentication-scheme: form
  resource:
    user-info-uri: https://api.twitter.com/oauth2/token